[build]
  # Publish the project root (contains portfolio.html and styles.css)
  publish = "."
  # No build command needed for a static site. If you add a build step later, set it here.
  command = ""

[dev]
  # Local dev server port for `netlify dev` (optional)
  port = 3000

[context.production.environment]
  NODE_ENV = "production"
